#!/bin/bash 

file=.tmp.serverload

for ((i=14;i<=18;i++));
do 
    if [ $i -eq 12 ];then
        continue;
    fi
    ssh heyang@shanN$i uptime 2>&1 | grep "load average" | sed "s/^/android$i /" | tee $file.android$i & 
done

sleep 2 

server=`cat $file.*  | sort  -g  -k 13 |  head -n1 | awk '{print $1}'`
echo ">>>>> now go server: $server"


